#!/usr/bin/env python3
"""build_registry — scans rules/ (+ industries/) for rule headings and (re)builds
`rules/_index.md`, the master registry.

Usage:
    python3 scripts/build_registry.py            # write rules/_index.md
    python3 scripts/build_registry.py --check     # verify in-sync + no dup IDs (CI gate)

A rule heading looks like:  ### PREFIX-001 — Title
Severity is read from the following `- **Severity:** <value>` line.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCAN_DIRS = ["rules", "industries"]
HEADING = re.compile(r"^#{2,4}\s+([A-Z0-9]+)-(\d{2,3})\s*[—\-–]\s*(.+?)\s*$")
SEVERITY = re.compile(r"\*\*Severity:\*\*\s*([a-zA-Z]+)")


def collect():
    rules = []          # (id, prefix, num, title, severity, relpath)
    seen = {}
    dups = []
    for d in SCAN_DIRS:
        base = ROOT / d
        if not base.exists():
            continue
        for f in sorted(base.rglob("*.md")):
            if f.name.startswith("_"):
                continue
            lines = f.read_text(encoding="utf-8", errors="replace").splitlines()
            rel = f.relative_to(ROOT).as_posix()
            for i, line in enumerate(lines):
                m = HEADING.match(line)
                if not m:
                    continue
                prefix, num, title = m.group(1), m.group(2), m.group(3)
                rid = f"{prefix}-{num}"
                sev = ""
                for look in lines[i + 1:i + 12]:
                    sm = SEVERITY.search(look)
                    if sm:
                        sev = sm.group(1).lower()
                        break
                    if HEADING.match(look):
                        break
                if rid in seen:
                    dups.append((rid, rel, seen[rid]))
                else:
                    seen[rid] = rel
                    rules.append((rid, prefix, int(num), title, sev, rel))
    return rules, dups


def render(rules):
    by_domain = {}
    for rid, prefix, num, title, sev, rel in rules:
        domain = rel.split("/")[1] if rel.startswith("rules/") else "industries"
        by_domain.setdefault(domain, []).append((prefix, num, rid, title, sev, rel))
    out = ["# Rule Registry",
           "",
           "> Auto-generated by `scripts/build_registry.py` — do not edit by hand.",
           f"> Total rules: **{len(rules)}**.",
           ""]
    for domain in sorted(by_domain):
        items = sorted(by_domain[domain], key=lambda r: (r[0], r[1]))
        out.append(f"## {domain}  ({len(items)})")
        out.append("")
        out.append("| ID | Title | Severity | File |")
        out.append("|----|-------|----------|------|")
        for prefix, num, rid, title, sev, rel in items:
            out.append(f"| `{rid}` | {title} | {sev or '—'} | `{rel}` |")
        out.append("")
    return "\n".join(out) + "\n"


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    rules, dups = collect()
    if dups:
        print("DUPLICATE RULE IDS:", file=sys.stderr)
        for rid, a, b in dups:
            print(f"  {rid}: {a} vs {b}", file=sys.stderr)
    target = ROOT / "rules" / "_index.md"
    content = render(rules)
    if "--check" in argv:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        ok = (current == content) and not dups
        print(f"registry: {len(rules)} rules, {len(dups)} duplicates, "
              f"{'IN SYNC' if current == content else 'OUT OF SYNC'}")
        return 0 if ok else 1
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    print(f"Wrote {target.relative_to(ROOT)} — {len(rules)} rules, {len(dups)} duplicates.")
    return 1 if dups else 0


if __name__ == "__main__":
    raise SystemExit(main())
